name: ETL CICD pipeline with test cases

#trigger
on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install dependancies
        run: pip install -r requirements.txt

      - name: run tests & enforce coverage
        run: pytest --cov=calc --cov-report=term --cov-report=html --cov-fail-under=80

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: html-coverage-report
          path: htmlcov/

  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job

    steps:
      - name: print message
        run: echo "deployment job started..."
